### ISSUE TITLE
Compatibility with ng2-http-interceptor

### ISSUE THREAD

**Issue by will093** [aitboudad/ng-loading-bar#12]
I am using the following HTTP interceptor plugin: 

https://www.npmjs.com/package/ng2-http-interceptor

It seems that the interceptor plugin does not work when also using this loading bar plugin.

**Comment by aitboudad** [comment]
Hi, 
`ng-loading-bar` rely on `Http` service by extending it due to the missing interceptor in `@angular/http`.
I don't know how `ng2-http-interceptor` manage extending `http` but I suggest to rely on the new HttpClient provided in angular `4.3` instead.

Note: The support of the new HttpClient will be added soon!

Thanks
